################################################################################
## Releasing the hounds in your local environment.
##
## Setup:
## $ gem install rubocop
##
## Run:
## $ rubocop ./path/to/file ./or/path/to/directory -c ./.hound.yml
##
################################################################################
AllCops:
  Include:
    - Rakefile
  Exclude:
    - app/data_generators/sipity/data_generators/**/*
    - db/**/*
    - bin/**/*
    - config/**/*
    - dragonfly/**/*
    - 'spec/fixtures/**/*'
    - 'vendor/**/*'
    - 'scripts/**/*'
    - 'tmp/**/*'
    - 'spec/support/sipity/command_repository_interface.rb'
    - 'spec/support/sipity/query_repository_interface.rb'
  RunRailsCops: true

ModuleLength:
  Exclude:
    - '**/*'

CaseEquality:
  Exclude:
    - app/decorators/sipity/decorators/comparable_simple_delegator.rb
    - spec/decorators/sipity/decorators/comparable_simple_delegator_spec.rb
    - app/decorators/sipity/decorators/base_object_with_composed_attributes_delegator.rb
    - spec/decorators/sipity/decorators/base_object_with_composed_attributes_delegator_spec.rb

MethodName:
  Exclude:
    - app/decorators/sipity/decorators.rb

Style/PredicateName:
  Exclude:
    - app/decorators/sipity/decorators/comparable_simple_delegator.rb
    - app/decorators/sipity/decorators/base_object_with_composed_attributes_delegator.rb

Style/ParallelAssignment:
  Exclude:
    - app/services/sipity/services/notifier.rb

MethodLength:
  Max: 10
  Description: 'Avoid methods longer than 10 lines of code.'
  CountComments: false
  Enabled: true
  Exclude:
    - app/conversions/**/*.rb
    - app/forms/sipity/forms/configure.rb
    - 'app/controllers/sipity/controllers/dois_controller.rb'
    - 'app/forms/sipity/forms/create_work_form.rb'
    - 'app/forms/sipity/forms/processing_form.rb'
    - 'app/mappers/sipity/mappers/etd_mapper.rb'
    - 'app/mappers/sipity/mappers/generic_file_mapper.rb'
    - 'app/repositories/sipity/queries/notification_queries.rb'
    - 'app/repositories/sipity/queries/permission_queries.rb'
    - 'app/repositories/sipity/queries/comment_queries.rb'
    - 'app/repositories/sipity/queries/enrichment_queries.rb'
    - 'app/repositories/sipity/queries/processing_queries.rb'
    - 'app/repositories/sipity/commands/processing_commands.rb'
    - 'spec/support/site_prism_support.rb'
    - 'app/services/sipity/guard_interface_expectation.rb'
    - 'app/services/sipity/services/notifier.rb'

LineLength:
  Description: 'Limit lines to 140 characters.'
  Max: 140
  Enabled: true

# TODO: Restore this to 100 lines
ClassLength:
  Max: 110
  Description: 'Avoid classes longer than 110 lines of code.'
  CountComments: false
  Enabled: true
  Exclude:
      - 'app/mappers/sipity/mappers/etd_mapper.rb'
      - 'app/mappers/sipity/mappers/generic_file_mapper.rb'

AlignParameters:
  Description: >-
                 Align the parameters of a method call if they span more
                 than one line.
  Enabled: true

BlockComments:
  Description: 'Do not use block comments.'
  Enabled: true
  Exclude:
    - spec/spec_helper.rb

CyclomaticComplexity:
  Description: 'Avoid complex methods.'
  Enabled: true
  Exclude:
     - app/conversions/**/*.rb
     - app/forms/sipity/forms/configure.rb
     - app/forms/sipity/forms/processing_form.rb

Metrics/PerceivedComplexity:
  Enabled: true
  Exclude:
     - app/conversions/**/*.rb
     - app/repositories/sipity/queries/processing_queries.rb
     - spec/support/site_prism_support.rb

Metrics/AbcSize:
  Enabled: true
  Max: 16
  Exclude:
     - app/conversions/**/*.rb
     - app/forms/sipity/forms/configure.rb
     - app/repositories/sipity/queries/*.rb
     - app/controllers/application_controller.rb
     - app/forms/sipity/forms/work_enrichments/attach_form.rb
     - 'app/repositories/sipity/commands/processing_commands.rb'
     - app/forms/sipity/forms/processing_form.rb
     - app/services/sipity/services/authentication_layer.rb
Delegate:
  Description: 'Prefer delegate method for delegations.'
  Enabled: false

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: true
  Exclude:
  - spec/**/*
  - lib/**/version.rb

EmptyLinesAroundBlockBody:
  Enabled: false

DotPosition:
  Description: 'Checks the position of the dot in multi-line method calls.'
  EnforcedStyle: trailing
  Enabled: true

Style/Encoding:
  Description: 'Use UTF-8 as the source file encoding.'
  Enabled: false

FileName:
  Description: 'Use snake_case for source file names.'
  Enabled: true

ParameterLists:
  Description: 'Avoid parameter lists longer than three or four parameters.'
  Enabled: true
  Max: 4
  Exclude:
  - app/data_generators/sipity/data_generators/permission_generator.rb
  - app/repositories/sipity/queries/work_queries.rb

PercentLiteralDelimiters:
  Description: 'Use `%`-literal delimiters consistently'
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()
  Enabled: true

RedundantReturn:
  Description: "Don't use return where it's not required."
  Enabled: false

StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  Enabled: false

WordArray:
  Description: 'Use %w or %W for arrays of words.'
  Enabled: false

AssignmentInCondition:
  Description: "Don't use assignment in conditions."
  Enabled: true
  Exclude:
    - bin/*

HandleExceptions:
  Description: "Don't suppress exception."
  Enabled: true
  Exclude:
    - bin/*
