Figaro.require_keys(
  'airbrake_api_key',
  'airbrake_host',
  'default_email_from',
  'default_email_return_path',
  'domain_name',
  'hesburgh_api_auth_token',
  'hesburgh_api_host',
  'noid_pool',
  'noid_port',
  'noid_server',
  'url_host'
)
