# Dear curious person:
#
# These are not the real keys to the kingdom. They are, however, used during
# development; Or more appropriately used as a frame of reference for our
# development.
#
# They are included so we can share what the keys should be.

curate_nd_url_for_etds: "https://curate.nd.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=etd"
curate_nd_url_show_prefix_url: "https://curate.nd.edu/show/"
default_email_from: 'sipity-development@nd.edu'
default_email_return_path: 'no-reply@nd.edu'
dragonfly_s3_access_key_id: 's3_key'
dragonfly_s3_bucket_name: 'bucket_name'
dragonfly_s3_root_path: 's3_root_dir'
dragonfly_s3_secret_access_key: 'secret'
dragonfly_s3_url_host: 'bucketname.aws.com'
dragonfly_secret: "12345"
ezid_client_default_shoulder: "doi:10.5072/FK2"
ezid_client_password: apitest
ezid_client_user: apitest
hesburgh_api_auth_token: '12345'
hesburgh_api_host: https://api.library.nd.edu/
noid_pool: 'pool_name'
noid_port: '3000'
noid_server: 'noidserver.com'
protocol: 'http'
airbrake_api_key: 'this-makes-no-sense'
airbrake_host: 'errbit.library.nd.edu'

# NOTE: cogitate_services_tokenizer_public_password is different for development and test environment.
# It is assumed that the development environment is connecting to a "live server" whereas test is
# often stubbing out the connection. The most important thing is that the `cogitate_services_tokenizer_public_password` is correct.
# The `cogitate_services_tokenizer_public_password` is the public key for the remote service. The cogitate token is signed with a
# corresponding private key and to detokenize via JWT, the public key must match.
development:
  domain_name: "localhost:3000"
  url_host: "http://localhost:3000"
  secret_key_base: 'bd6953190e19dabc215af75a5c856f584dca49a3ab729696946a80ec50f46094d4643d908b88b07011f898f5c6748f2ffa832c96bae409e5462f2cf3055f1ee7'
  curate_batch_user_pid: "batch_user_pid"
  curate_batch_group_pid: "batch_group_pid"
  cogitate_services_tokenizer_public_password: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxhwhuijWgzTA0Gzuih5E\n2aueEF/9v1a6fLddhi9TtDT15zc2fAcQulieyJ5Jk0V+Xp6Fs1w+MEikO2YbLmdT\nEz07et/xjdhCKKiLaYwAl5w2F4/BlpSD17x998uS/lkOZkOHmXpDZk14gHM9IiNN\nK++jQaTcChfCDdG9kjMjKq2OHMye052PH9GYSXOsGfXaT1ijRbksnZmj5kcG2mJ2\nNRr1pqBeYWjvtY8y488p/ymGTg5Xu/BvxtFKzVEN+lBOVcZaCA9/DeeYCdlFgeLj\nDqY3RI+NaoJyqA5yJYtgBcnj+h86XMOWgTnQ3GfELkELEeK+49DhisIfRJFaYfBo\ndQIDAQAB\n-----END PUBLIC KEY-----\n"
  cogitate_services_remote_server_base_url: "https://cogitate-staging.library.nd.edu"
  cogitate_services_tokenizer_encryption_type: 'RS256'
  cogitate_services_tokenizer_issuer_claim: "https://library.nd.edu"
  cogitate_services_after_authentication_callback_url: 'https://localhost:3000/after_authentication'
  curate_batch_data_mount_path: "local/data"
  curate_batch_queue_mount_path: "local/queue"

test:
  domain_name: "localhost:3000"
  url_host: "http://localhost:3000"
  secret_key_base: 'bd6953190e19dabc215af75a5c856f584dca49a3ab729696946a80ec50f46094d4643d908b88b07011f898f5c6748f2ffa832c96bae409e5462f2cf3055f1ee7'
  curate_batch_user_pid: "batch_user_pid"
  curate_batch_group_pid: "batch_group_pid"
  cogitate_services_tokenizer_public_password: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuZYpQKfFJ2CfdyPTMj7b\nQBALe58cWAN+B6tyLBPozDRe7OcJPs/PnOtaPcvdk0RQcTxCtTkgb3Z1bTeQam+l\n3Hy5byCXcojCQPbQes+jGQ62W59aC6li/v0QakO68kCr/HAI49HBhMp59LOVNWUQ\nZNIgnbQxWT3N/0guLPbN2d+qTSW906YRjanVE4daKQ0TNZKa8Py1PP8ey0h2ipoW\nkr0WAz24AgdXUkQ4Y1RdeEs71On5exx8WtrUBMluNIG4neJwvkiaXWMDS2eQU2Oy\nV/L1dkNUrpnNuUb3vhlfyTKEsYUpt0ZoMVyddL1Vzuw/GmGuc4a1y+P6rmHXxQJR\n7wIDAQAB\n-----END PUBLIC KEY-----\n"
  cogitate_services_remote_server_base_url: "https://localhost:3001"
  cogitate_services_tokenizer_encryption_type: 'RS256'
  cogitate_services_tokenizer_issuer_claim: "https://library.nd.edu"
  cogitate_services_after_authentication_callback_url: 'https://localhost:3000/after_authentication'
  curate_batch_data_mount_path: "tmp/data"
  curate_batch_queue_mount_path: "tmp/queue"
