# Dear curious person:
#
# These are not the real keys to the kingdom. They are, however, used during
# development; Or more appropriately used as a frame of reference for our
# development.
#
# They are included so we can share what the keys should be.
development: &development
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>

test:
  <<: *development
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  admin_name: <%= Figaro.env.admin_name %>
  admin_email: <%= Figaro.env.admin_email %>
  admin_password: <%= Figaro.env.admin_password %>
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>
  ezid_cloent_default_shoulder: <%= Figaro.env.ezid_client_default_shoulder %>
  ezid_client_user: <%= Figaro.env.ezid_client_user %>
  ezid_client_password: <%= Figaro.env.ezid_client_password %>

staging:
  <<: *production

pre_production:
  <<: *production
